// This is an autogenerated file from Firebase Studio.

import {startDevServer} from '@genkit-ai/next/dev';

// Import flows from your application.
// Update the import path if the filename changed
import './flows/interpret-mood.js'; // Keep original name or update if renamed, e.g., './flows/generate-music-recommendations.js'

startDevServer();
